# Generated by Django 4.2.4 on 2023-08-25 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellularModuleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Idle', 'Idle'), ('Testing', 'Testing'), ('Debug', 'Debug')], default='IDLE', max_length=10)),
                ('mac_address', models.CharField(max_length=17, null=True, unique=True)),
                ('ip', models.GenericIPAddressField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_series_name', models.CharField(max_length=30, null=True, unique=True)),
                ('num_lan', models.IntegerField(default=0, null=True)),
                ('num_sim_slot', models.IntegerField(default=0, null=True)),
                ('num_sd_card', models.IntegerField(default=0, null=True)),
                ('cpu_arch', models.CharField(choices=[('armhf', 'armhf'), ('amd64', 'amd64')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestbedNport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestbedWifiAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ssid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WifiModuleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WifiModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, null=True, unique=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.wifimodulebrand')),
            ],
        ),
        migrations.CreateModel(
            name='WifiModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=30, null=True, unique=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.wifimodulemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TestbedSparkPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_id', models.CharField(max_length=10, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='TestbedAWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.CharField(max_length=50, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='TestbedAIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('encryption', models.CharField(blank=True, choices=[('Symmetric', 'Symmetric'), ('X509', 'X509')], max_length=10, null=True)),
                ('identity_cert', models.CharField(max_length=100, null=True)),
                ('identity_pk', models.CharField(max_length=100, null=True)),
                ('identity_cer_content', models.CharField(max_length=100, null=True)),
                ('identity_pk_content', models.CharField(max_length=100, null=True)),
                ('downstream_certs_ca_cert_file', models.CharField(blank=True, max_length=100, null=True)),
                ('downstream_certs_ca_pk_file', models.CharField(blank=True, max_length=100, null=True)),
                ('downstream_certs_trusted_ca_file', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='TestbedAID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('encryption', models.CharField(choices=[('Symmetric', 'Symmetric'), ('X509', 'X509')], max_length=10, null=True)),
                ('connection_string', models.CharField(max_length=100, null=True)),
                ('root_ca_cert_file', models.CharField(max_length=100, null=True)),
                ('ca_cert_file', models.CharField(max_length=100, null=True)),
                ('ca_pk_file', models.CharField(max_length=100, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=20, null=True)),
                ('sim_slot', models.IntegerField(null=True)),
                ('pin_code', models.CharField(max_length=4, null=True)),
                ('apn', models.CharField(max_length=20, null=True)),
                ('operator', models.CharField(choices=[('Chunghwa', 'Chunghwa'), ('TMobile', 'TMobile')], max_length=20, null=True)),
                ('iccid', models.CharField(max_length=20, null=True, unique=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='SDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=20, null=True)),
                ('sd_card_slot', models.IntegerField(null=True)),
                ('capability', models.IntegerField(null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='NPortSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_port', models.IntegerField(null=True)),
                ('nport_port', models.IntegerField(null=True)),
                ('cabel_model', models.CharField(choices=[('RS232', 'RS232'), ('RS422', 'RS422'), ('RS485', 'RS485')], max_length=10, null=True)),
                ('baud_rate', models.IntegerField(choices=[(1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (19200, '19200'), (115200, '115200')], null=True)),
                ('mode', models.CharField(choices=[('Realcom', 'Realcom'), ('RFC2217', 'RFC2217'), ('Telnet', 'TELNET')], max_length=20, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('nport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.testbednport')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model_name', models.CharField(max_length=30, null=True, unique=True)),
                ('device_series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.deviceseries')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.devicemodel'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='testbed_wifi_ap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.testbedwifiap'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CellularModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, null=True, unique=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.cellularmodulebrand')),
            ],
        ),
        migrations.CreateModel(
            name='CellularModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, null=True, unique=True)),
                ('module_id', models.IntegerField(null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.cellularmodulemodel')),
            ],
        ),
    ]
